version: '2'
services:
  db:
    image: mysql:5.7
    volumes:
     - ./shared/mysql/dump/:/docker-entrypoint-initdb.d
    environment:
     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
     MYSQL_USER: ${MYSQL_USER}
     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
     MYSQL_DATABASE: ${MYSQL_DATABASE}
     APP_NAME: ${APP_NAME}
    ports:
     - ${DB_PORT}:3306
  app:
    build: ./docker-images/symfony
    depends_on:
     - db
    volumes:
     - ./src/symfony:/var/www/html/${APP_NAME}
     - ./configs/parameters.yml:/var/www/html/${APP_NAME}/app/config/parameters.yml
  web-srv:
    build: ./docker-images/nginx
    ports:
     - ${WEB_SRV_PORT}:80
    volumes:
     - ./nginx/configs/conf.d/:/etc/nginx/conf.d/
     - ./nginx/configs/nginx.conf:/etc/nginx/nginx.conf
     - ./nginx/configs/.htpasswd:/etc/nginx/.htpasswd
#     - ./nginx/ssl/:/etc/nginx/ssl/
    volumes_from:
     - app